### ISSUE TITLE
Implement Bike Agent behaviour

### ISSUE THREAD

**Issue by paydelimon22** [paydelimon22/TC2008B#3]
Implement the `Bike` agent behavior.

- [ ] Have permanent destination they must reach.
- [ ] Have access to all the Roads on the map (no traffic) in order to plan
    their routes.
- [ ] Move only towards the direction of the road they are on to roads without
    another bike.
- [ ] Stop when there are no available roads.
- [ ] Stop at red lights.
- [ ] Despawn when reaching destination.

**Comment by BassedWarrior** [comment]
This issue should really only be about the `Bike` agents, since all other
agents are static and merely there for logical purposes. The only other
meaningful agents could be the `TrafficLight` agents, but even then the base
implementation of them already implements the only interaction they have, which
is to switch every 10 steps. Hence I believe renaming and rewriting this issue
could be in order for better clarity.

This is not a change of the scope of the issue per se, but rather a
clarification of it.
